### ISSUE TITLE
🐛 Error: URL to video is not working

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#113]
# Error Symptoms

When you want to select a video like so `/storage/efs/cc_me0l0PfA` you get an error. The page is hosted on S3 and Delivered over CloudFront, so CloudFront is looking for a file that dose not exists. Doing issue #111 might solve this problem.

# Error Message

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: index
RequestId: 294727926ACF656F
HostId: 44PplC0TaoHCDgZ9IivAwKF3RJStsNIhALc0gjD2gEQN6AEwldbZaOwA+d/8znHlj1ocWtSJYDc=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

**Comment by acidbiscuit** [comment]
@davidgatti Need to test on production server after #115 is merged and deployed. Locally it works correctly, but some infrastructure aspects can interfere.

**Comment by davidgatti** [comment]
I did merge the PR (thank you for commenting out the code). But it did not solve the problem, The problem is related to issue #111. The problem is that CloudFront tries to ask S3 for the file, since it thinks that is a folder, and when there is no folder to be seen then you get the file not found.

We need to generate all the pages, including all the video URLs. This way this will work + google will be able to index all the videos with their titles. 

I hope this makes sense.

**Comment by davidgatti** [comment]
@acidbiscuit they are still not working, but we are close 99% we are there :) check the live page here: https://awsvideocatalog.com/ the problem seams to be pretty trivial.

**Comment by acidbiscuit** [comment]
@davidgatti Aside from generation issue, I've found invalid URLs for "small-video" component. Thus clicking on video thumbnail was causing 404 error which is unrelated to page generation. Please, check #120
