### ISSUE TITLE
🎁 New feature: Reorganize the static folder since it is a bit of a mess

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#125]
# My Problem

Reorganize the static folder since it is a bit of a mess

# Solution

set better names for files, group things together in to folders with easy to understand names etc.

**Comment by acidbiscuit** [comment]
@davidgatti 
I've pushed a WIP branch with suggested structure for static content storage. This is a first step in organizing data storage in the project.  
Notes about proposed structure:
- Every entity is stored in `~/static/content` folder in it's own file `categories`, `services`, `videos`;  
- There is a clear relation established between the entities;
- Searching for specific data with slugs from URLs will require minimum processing and searching, since all slugs are already provided in the storage;
- Data is ready to be stored externally or put in the DB.

The last point is also one of performance concerns if catalog data is expected to grow or be managed externally. Currently whole JSON files are being loaded as part of the application code. WIth updated storage structure, it is also possible to serve JSON files with maximum caching or even expose minimal API endpoints to get specific parts of data.

It will still require additional changes in current data fetching implementation to simplify the whole process.

What do you think?

**Comment by davidgatti** [comment]
So you did add the content folder and organized the files in a more logical structure to represent the pages in files. If this is true then I'd like to propose something even more structured:

1. rename `content` to `database` - to make it clear that this is the dynamic data for the website
1. a bit different folder structure:

```
[database]
    [categories]
    index.json
        [services]
        index.json 
            videos
            chatbot.json
            ec2.json
            lambda.json
            individual_services_in_separated_files.json
```

Where things within `[]` is a folder. The idea is to visually show the page structure as a folder structure. This way in the future let say that in the category folder there will be something else then services, you can make a new folder within that one, and you get to visually know the structure of the static DB.

Also I'd like to keep the individual services in separated files, because it is easier to manage, work with and and track changes over time.

# The future

When it comes to the future, I will add new services as they come, so the local DB will grow with AWS. But I'm not planing to move the data in a database of any sorts, because I do want to keep the hosting costs to a minimum. Right now the site is built, the content copied to S3 and delivered using CloudFront, this way I could care less about costs. Of course in the future I want to add extra features that will be stored externally, but they won't be related to this basic service list, because this stuff will change over time very slowly so I don't like to pull over and over the same thing that dose not change.

# More context

> Currently whole JSON files are being loaded as part of the application code

Can you give me more context, like an article or YT video that explains this part?

**Comment by acidbiscuit** [comment]
@davidgatti Thank you for such detailed description.

### More context
I am not sure if there is a dedicated video on the matter. My explanation may be more useful.  
Currently, we store data in JSON that resides within the project. These files, for example, `services.json` are located in `static` folder, which is used by Nuxt.js to serve files without webpack processing and also make them accessible via direct URL, for example, http://localhost:3000/services.json. Though, these files in current application are also imported in JS files. This means, that JSON files are put into a separate bundle and are loaded together with the application and are also inlined in output HTML.  

For example, page https://awsvideocatalog.com/migration_&_transfer loads all categories, all services and all videos details, while only specific services list is relevant on that page. JSON chunks get cached between pages, but they are still loaded and parsed for every page.

As for suggested structure, I have two notes:
1) What is the expected content of `index.json` file in `services` folder, as an example?  
2) There is no performance improvement, unless every chunk get loaded dynamically via an HTTP request.

**Comment by davidgatti** [comment]
OK, so I'm no Nuxt.js expert I know very little how it works, I'm someone that started 20 years ago making website when Wordpress was at version 0.9 ;) So I know what a website is and how it works, and are always amused by how things got overengineered over the years. I also did before I knew Nuxt.js existed a mini framework to make static websites: https://www.npmjs.com/package/@0x4447/avocado due to the craziness that is going on with the web, and wanted something that can be indexed by Google without a server running in the background.

I'm saying all fo this to say, that I want a simple page that just has txt files that the browser can understand, and Google can index. I could care less about "it feels like a desktop app" 

So I'd be very happy if it would be possible to disable the idea to load the whole page with all the components just in case you want to click around. I'm ok, with building each individual page, that just has what it needs to work, and when you click somewhere else you download a new set of files for the new specific page.

# Notes anwsers

1. the `index.json` files that are within the folder contains the content of the folder name. For example clock on each folder here: https://github.com/0x4447/0x4447_product_secure301/tree/master/07_Resources/Lambda/s301_lambda_redirect - the index files represent the main entry point and contains the resources of the folder name. So if you go to the `Lambda` folder, and check the `_index.json` it has all that is needed to configure the Lambda itself, everything else are extra resources related to the Lambda.
1. I don't care about performance, I care about costs for running a basic website that display a list of items :)
