### ISSUE TITLE
🎁 New feature: Alt tag for video Thumbnils

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#130]
# My Problem

No Alt tag for video thumbs

# Solution

Video thumbnails must have the title of the video set as the alt text

**Comment by acidbiscuit** [comment]
@davidgatti 

Image alt attributes appear to be correct in the latest app version. Provided an example below. Is expected behavior different for you?
![Example](https://user-images.githubusercontent.com/11949520/92321130-2bc0cd00-f05a-11ea-9d9c-3b3acc4472c8.png)

**Comment by davidgatti** [comment]
Hmm in this case, if there is an Alt, when I keep my mouse pointer on the thumbnail, shouldn't a tool tip show up?

**Comment by acidbiscuit** [comment]
@davidgatti `title` attribute is responsible for that. Will add `title` attributes for videos.
