### ISSUE TITLE
🎁 New feature: Move youtube video id & thumbnail generation from UI to fetching layer

### ISSUE THREAD

**Issue by acidbiscuit** [aws-videos-catalog/avc_website#143]
# My Problem

Currently there are multiple places within the app where youtube video id and thumbnails are used. This data is not present in static content data set, thus has to be generated. Current way of getting video id and thumbnails from video link is happening in the place of consumption of data by components, which introduces minor performance cost increase, code duplication and potential exceptions in case of missing/invalid data. Following the best practices, presentational UI components should not be responsible for data formatting.

# Solution

Format video data on the stage of fetching data to generate video id and thumbnail with set of purified and reusable helper functions.

**Comment by davidgatti** [comment]
Question: right now the thumbnail is pulled live from YT, if you were to implement your work, this image would be pulled form YT at build time? And then served from our side? Or you are saying you just need to move the code in a better place in the framework responsible for manipulating the data, and not displaying it?

**Comment by acidbiscuit** [comment]
@davidgatti Thumbnails stay on YT, just need to move logic into a single place and out of presentational components.

**Comment by davidgatti** [comment]
Aa ok, in this case please do it.
