### ISSUE TITLE
🎁 New feature: Create a separate component for video player and ads

### ISSUE THREAD

**Issue by acidbiscuit** [aws-videos-catalog/avc_website#147]
# My Problem

Currently main video player and side ads template is mirrored on both `_video` and `_name` pages. Any changes made regarding this section require changes to both pages. This does not follow DRY principle and can be considered a poor practice.  
Upcoming changes of adding custom styles instead of bootstrap columns will require duplication of CSS code.

# Solution

As first step of cleaning up and unifying video playback page, it is suggested to create a single component `VideoPlayerMain` that will accept `video` and `description` props and handle section layout and styles.

**Comment by davidgatti** [comment]
Sounds good.
