### ISSUE TITLE
🎁 New feature: consystent margins across the site

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#169]
# My Problem

The pages has margins, that are not consistent across the page

# Solution

Use the margins from the video page as reference, and make all margins to match those

![Screen Shot 2020-10-03 at 9 00 32 AM](https://user-images.githubusercontent.com/411114/94985740-63d40680-0559-11eb-8d5c-65e4dcfc86fe.png)

**Comment by acidbiscuit** [comment]
@davidgatti Please, clarify which margin should be applied.

From video related videos section - [30px](https://prnt.sc/v21dga)
Or from videos list section - [15px](https://prnt.sc/v21gxw)

**Comment by davidgatti** [comment]
From this view: https://awsvideocatalog.com/compute/ec2/LNqRvP6Xvrw - the view that shows the video.

**Comment by acidbiscuit** [comment]
@davidgatti This one was resolved as part of #176 . Please, let know if any additional changes required.

**Comment by davidgatti** [comment]
aa cool, looks OK now.
