### ISSUE TITLE
🎁 New feature: Sticky footer

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#173]
# My Problem

The footer dose not stick to the end of the page, when there is not enough content

# Solution

Make it stick

![Screen Shot 2020-10-03 at 9 05 27 AM](https://user-images.githubusercontent.com/411114/94985849-3b98d780-055a-11eb-81ca-29582db242c3.png)

**Comment by acidbiscuit** [comment]
@davidgatti I'd like to discuss the implementation of such sticky footer.

If we take in account that number of cards change depending on device screen width, we will have different amount of space for the footer. In some cases, we will have only 1 cell out of 6 (as per screenshot layout) for the footer. I'm not confident if that is going to play well.  
Also footer plays a role of an indicator and spacer at the end of the page to ensure that page content is not hitting the bottom of the screen, which is considered a bad practice in UI. Footer has to be clearly distinguished from page content.

I need your input on what problem are we trying to solve by putting the footer alongside the content.

**Comment by davidgatti** [comment]
The problem we want to solve, is the situation where there is only one row, and the rest of the page is empty. Having the footer at the bottom of the page in that case would look nicer/more organized. This is a good example: https://getbootstrap.com/docs/4.5/examples/sticky-footer/

**Comment by acidbiscuit** [comment]
@davidgatti Thank you for providing an example, I misunderstood initial request. Your example makes sense.
