### ISSUE TITLE
🐛 Error: OG tags are all wrong

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#182]
# Error Symptoms

When you share the URL to the site on places that make a preview, the OG tags have the wrong data, the images are missing, the title is wrong and the description is wrong.

**Comment by acidbiscuit** [comment]
@davidgatti 
Any specifics will be appreciated.
I've tested in messengers and dedicated tools - meta tags appear to work correctly.

See an [example](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fawsvideocatalog.com%2Fnetworking_%26_content_delivery) with Facebook sharing debug

**Comment by davidgatti** [comment]
Interesting on slack it is all broken. See what is missing for Slack to be happy?

![Screen Shot 2020-10-05 at 10 08 49 AM](https://user-images.githubusercontent.com/411114/95054996-f52ab080-06f2-11eb-8ab3-af0eb4ef99f9.png)
