### ISSUE TITLE
Research about folders

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#19]
Figure out the difference about the asset folder and the static folder

**Comment by tolgaouz** [comment]
Directly quoting from documentation, 

By default, Nuxt uses vue-loader, file-loader and url-loader webpack loaders for strong assets serving. You can also use the static directory for static assets.

So assets are being loaded using webpack for optimized or minified version bundling. Statics are not touched by webpack. We can use module loadings, SASS, SCSS etc with assets

**Comment by davidgatti** [comment]
OK, in this case lets keep this in mind and take advantage when needed.
