### ISSUE TITLE
❓ Question: How random is random?

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#190]
# My Question

We have a section of the project that displays the products - in theory the picking of a product to be displayed should be random, but if I check the stats of the visits. I see that Rsyslog server is being displayed 2.7 times more often - not very random :) 

How well was this implementation done?

**Comment by acidbiscuit** [comment]
@davidgatti Current implementation is random enough.

Here is a test with 100000 random picks between 0 and 2.
https://jsfiddle.net/w0nydqxb/

As you can see - occurrences are even. Randomness may not be enough for sensitive data, but enough for this case :)

**Comment by davidgatti** [comment]
Interesting, so maybe people just liked the Rsyslog ad more then the rest I guess :) thank you for the check.
