### ISSUE TITLE
🎁 New feature: Integrate GoogleTagManager with dedicated plugin

### ISSUE THREAD

**Issue by acidbiscuit** [aws-videos-catalog/avc_website#194]
# My Problem
Currently, GTM script and configuration is added right inside Vue.js component `template` of `default.vue` layout. This is considered a bad practice and can potentially lead to rendering issues.  
Additionally, GTM script is an application level script and should be imported globally with respect to Nuxt.js framework lifecycles. For example, if another layout is added, the whole script would need to be copied completely and maintained in 2 places.  

# Solution

It is recommended to use [@nuxtjs/gtm](https://github.com/nuxt-community/gtm-module) module. Cons of using the module:  
- [Fully configurable](https://github.com/nuxt-community/gtm-module#options)
- Can be disabled for development and testing
- GTM key can be set via environmental variables to remove it from Github repository
- Correctly tracks route change events as `pageView` in analytics
- Ensures correct integration with Nuxt.js for all application modes

**Comment by davidgatti** [comment]
Epic, I like it :)
